# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6ebe72d197ff326ab086f7baec2c1a7a"
name = "lean-capital-app"
handle = "lean-capital-app-4"
application_url = "https://c9e3c6f5b82384c2bab634463a8b3d40.serveo.net"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "poc-remix.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://c9e3c6f5b82384c2bab634463a8b3d40.serveo.net/auth/callback",
  "https://c9e3c6f5b82384c2bab634463a8b3d40.serveo.net/auth/shopify/callback",
  "https://c9e3c6f5b82384c2bab634463a8b3d40.serveo.net/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
